server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounter
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format-sql: true
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: localhost
    port: 1025

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
            auth: true
            starttls:
              enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  messages:
    basename: messages, email
    encoding: UTF-8
    fallback-to-system-locale: true

messaging:
  emailconfirm:
    from: service@accounterproject.com
    subject: Confirm your email
