server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounter
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format-sql: true